experiment:
  result_dir: D:/project/TAAS_After_Revision/result2
  bc_actor_dir: D:/project/TAAS_After_Revision/bc_actor
  bc_actor_name:
    straight_line: Agent181_100_-4_Harfang_GYM
    serpentine: Agent77_86_-600_Harfang_GYM
    circular: None
  expert_data_dir: D:/project/TAAS_After_Revision/expert_data

network:
  ip: 172.27.58.131

